site_name: iRODS
repo_url: https://github.com/irods/irods_docs
site_description: Control Your Data
site_author: iRODS Consortium
site_dir: site
docs_dir: docs
theme: readthedocs
extra_css:
 - irods.css

markdown_extensions:
 - admonition
 - attr_list
 - def_list

pages:
 - 'index.md'
 - Why iRODS?: 'why_irods.md'
 - Releases:
    - Release Notes: 'release_notes.md'
    - Legacy Release Notes: 'legacy_release_notes.md'
 - 'developers.md'
 - Plugins:
    - Plugin Interfaces: 'plugins/plugin_interfaces.md'
    - Pluggable Microservices: 'plugins/pluggable_microservices.md'
    - Composable Resources: 'plugins/composable_resources.md'
    - Pluggable Authentication: 'plugins/pluggable_authentication.md'
    - Pluggable Network: 'plugins/pluggable_network.md'
    - Pluggable Database: 'plugins/pluggable_database.md'
    - Pluggable RPC API: 'plugins/pluggable_rpc_api.md'
    - Pluggable Rule Engine: 'plugins/pluggable_rule_engine.md'
    - iRODS Rule Language: 'plugins/irods_rule_language.md'
 - Manual:
    - 'manual/download.md'
    - 'manual/installation.md'
    - 'manual/upgrading.md'
    - 'manual/configuration.md'
    - Users & Permissions: 'manual/users_and_permissions.md'
    - Backing Up: 'manual/backing_up.md'
    - 'manual/federation.md'
    - Control Plane: 'manual/control_plane.md'
    - Distributing iCommands: 'manual/distributing_icommands.md'
    - 'manual/glossary.md'
    - Best Practices: 'manual/best_practices.md'
    - 'manual/troubleshooting.md'
    - Tips and Tricks: 'manual/tips_and_tricks.md'
 - iCommands:
    - 'icommands/administrator.md'
    - 'icommands/user.md'
    - 'icommands/metadata.md'
    - 'icommands/tickets.md'
    - 'icommands/groupadmin.md'
 - Doxygen:
    - 'doxygen/index.html'

