site_name: iRODS Docs
repo_url: https://github.com/irods/irods_docs
site_description: Control Your Data
site_author: iRODS Consortium
site_dir: site
docs_dir: docs
google_analytics:
 - UA-49704995-1
 - auto
theme: readthedocs
extra_css:
 - irods.css
extra_javascript:
 - irods.js

markdown_extensions:
 - admonition
 - attr_list
 - def_list


pages:
 - Home: 'index.md'
 - Why iRODS?: 'why_irods.md'
 - Release Notes: 'release_notes.md'
 - Developers: 'developers.md'
 - Getting Started:
    - Download: 'manual/download.md'
    - Installation: 'manual/installation.md'
    - Upgrading: 'manual/upgrading.md'
 - Plugins:
    - Plugin Interfaces: 'plugins/plugin_interfaces.md'
    - Pluggable Microservices: 'plugins/pluggable_microservices.md'
    - Composable Resources: 'plugins/composable_resources.md'
    - Pluggable Authentication: 'plugins/pluggable_authentication.md'
    - Pluggable Network: 'plugins/pluggable_network.md'
    - Pluggable Database: 'plugins/pluggable_database.md'
    - Pluggable RPC API: 'plugins/pluggable_rpc_api.md'
    - Pluggable Rule Engine: 'plugins/pluggable_rule_engine.md'
    - Dynamic Policy Enforcement Points: 'plugins/dynamic_policy_enforcement_points.md'
    - iRODS Rule Language: 'plugins/irods_rule_language.md'
 - System Overview:
    - Process Model: 'manual/process_model.md'
    - Control Plane: 'manual/control_plane.md'
    - Configuration: 'manual/configuration.md'
    - Users & Permissions: 'manual/users_and_permissions.md'
    - Backing Up: 'manual/backing_up.md'
    - Federation: 'manual/federation.md'
    - Distributing iCommands: 'manual/distributing_icommands.md'
    - Glossary: 'manual/glossary.md'
    - Best Practices: 'manual/best_practices.md'
    - Troubleshooting: 'manual/troubleshooting.md'
    - Tips and Tricks: 'manual/tips_and_tricks.md'
 - iCommands:
    - 'icommands/administrator.md'
    - 'icommands/user.md'
    - 'icommands/metadata.md'
    - 'icommands/tickets.md'
    - 'icommands/groupadmin.md'
 - Doxygen: 'doxygen/index.html'
 - Legacy Release Notes: 'legacy_release_notes.md'

